name: iOS CI

# Dispara o workflow quando há push ou pull request na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Passo 1: Clonar o repositório
      - name: Check out the repository
        uses: actions/checkout@v3

      # Passo 2: Configurar a versão do Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4' # Altere conforme a versão necessária para o seu projeto

      # Passo 3: Set up Signing Certificate
      - name: Set up Signing Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > ios_development.cer
          security import ios_development.cer -P "$CERTIFICATE_PASSWORD" -A

      # Passo 4: Set up Provisioning Profile
      - name: Set up Provisioning Profile
        env:
          MOBILEPROVISION_BASE64: ${{ secrets.APPLE_PROFILE }}
        run: |
          echo "$MOBILEPROVISION_BASE64" | base64 --decode > ApplePie.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv ApplePie.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
      # Passo 5: Configurar a versão do Xcode
      - name: Install CocoaPods
        run: pod install --repo-update

      # Passo 6: Executar o SwiftLint para verificar o código
      - name: Install SwiftLint
        run: |
         brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint

      # Passo 7: Realizar o build e executar testes unitários
      - name: Build and test the project
        run: |
          xcodebuild -workspace "ApplePie.xcworkspace" \
          -scheme "ApplePie" \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
          clean test CODE_SIGNING_ALLOWED=NO

      # Passo 8: Exibir resultados de teste
      - name: Show test results
        if: always()
        run: |
          echo "Verifique os logs de saída para resultados detalhados de testes."


